Merging of Dev (Assignment 3) into Master
CS3219-AY2324S1/ay2324s1-course-assessment-g32 pull request #140
Opened 2023-10-13 10:33 UTC by anthonynmh

2023-10-13 14:14 UTC, cadencjk requested changes
Need to remove line 23 from README

2023-10-13 16:24 UTC, venuslimm requested changes

2023-10-13 16:24 UTC, venuslimm commented on backend/server/repositories/userRepoMySql.js
> +  // userId = userId['_userId'];
I think these should be removed

2023-10-13 16:24 UTC, venuslimm commented on package.json
Yes, it needs to be. README.md needs to be updated if this modification is made to package.json

2023-10-13 16:36 UTC, JrmCkh approved these changes
LGTM

2023-10-13 19:14 UTC, anthonynmh commented on package.json
Updated readme and package.json

2023-10-13 19:14 UTC, anthonynmh commented on README.md
> +4. Run the SQL statements in `./Auth/schema.sql` on the terminal.
removed

2023-10-13 19:14 UTC, anthonynmh commented on backend/server/repositories/userRepoMySql.js
> +  // userId = userId['_userId'];
removed

2023-10-14 03:58 UTC, cadencjk approved these changes
LGTM

2023-10-14 06:01 UTC, venuslimm approved these changes
LGTM

2023-10-14 06:05 UTC, merged