Merge assignment 3 to assignment 4
CS3219-AY2324S1/ay2324s1-course-assessment-g32 pull request #214
Opened 2023-11-04 11:02 UTC by cadencjk

2023-11-04 12:14 UTC, lhy-hoyin requested changes
Generally okay, need some slight changes for consistency

2023-11-04 12:14 UTC, lhy-hoyin commented on Auth/.gitignore
Maybe keep the EOF new line?

2023-11-04 12:14 UTC, lhy-hoyin commented on Question/.gitignore
Keep EOF new line

2023-11-04 12:14 UTC, lhy-hoyin commented on User/.gitignore
Keep EOF new line

2023-11-04 12:14 UTC, lhy-hoyin commented on User/initdb/02-host-privilege.sql
Keep EOF new line

2023-11-04 12:14 UTC, lhy-hoyin commented on frontend/src/pages/Question/QuestionDescription/QuestionDescription.css
Add EOF new line

2023-11-04 15:11 UTC, cadencjk commented on Auth/.gitignore
Okay done

2023-11-04 15:12 UTC, cadencjk commented
> Generally okay, need some slight changes for consistency

Okay added EOF line

2023-11-05 05:49 UTC, lhy-hoyin approved these changes
LGTM

2023-11-05 05:55 UTC, merged